version: '3'
services:
  omnia_relay:
    image: omnia-relay
    build:
      context: "."
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"
      - "../dapptools/src/seth/:/opt/seth/"
      - "./config/relay-ethereum-sepolia.json:/home/omnia/omnia.json"
      - "./config/relay-ethereum-sepolia.json:/opt/omnia/config/relay.json"
      - "./docker/keystore/:/home/omnia/.ethereum/keystore/"
      - "./docker/spire/config/relay_config.hcl:/home/omnia/spire.hcl"
    environment:
      ETH_RPC_URL: "https://rpc-sepolia.rockx.com/"
      CFG_ETH_CHAIN_ID: 11155111
      ETH_FROM: "0xe3ced0f62f7eb2856d37bed128d2b195712d2644"
      ETH_GAS_SOURCE: "node"
      ETH_MAXPRICE_MULTIPLIER: 1
      CFG_ETH_KEYS: "/root/keystore"
      CFG_ETH_PASS: "/root/keystore/pass"
      OMNIA_VERBOSE: "true"
      SPIRE_CONFIG: "/home/omnia/spire.hcl"
      CFG_SPIRE_RPC_ADDR: "0.0.0.0:9102"
      OMNIA_LOG_FORMAT: "json"
      ETH_VALUE: 1

networks:
  default:
    name: omnia_network
